ALTER TABLE users
    ADD COLUMN is_verified BOOLEAN NOT NULL DEFAULT FALSE;

CREATE TABLE managers (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email        VARCHAR(100) NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    full_name    VARCHAR(100),
    is_active    BOOLEAN NOT NULL DEFAULT TRUE,
    created_at   TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at   TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_managers_email UNIQUE (email)
);

CREATE TABLE otp_tokens (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    BIGINT NOT NULL,
    token      VARCHAR(10) NOT NULL,
    purpose    VARCHAR(40) NOT NULL,
    expires_at TIMESTAMP WITH TIME ZONE NOT NULL,
    is_used    BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_otp_tokens_user FOREIGN KEY (user_id) REFERENCES users (id)
);

CREATE INDEX idx_otp_tokens_user_purpose_used ON otp_tokens (user_id, purpose, is_used);
CREATE INDEX idx_otp_tokens_used_expiry ON otp_tokens (is_used, expires_at);

